name = "imglegal"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "imglegal.app", custom_domain = true }
]

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "imglegal-images"

[assets]
directory = "./public"
binding = "ASSETS"

[unsafe]
  [[unsafe.bindings]]
  name = "UPLOAD_RATE_LIMITER"
  type = "ratelimit"
  namespace_id = "1001"
  simple = { limit = 10, period = 60 }
